import { z } from "zod";
import { randomUUID } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { Context } from "../lib/context.js";
import type { BRollClip, Platform } from "../types.js";
import { PLATFORM_DIMENSIONS } from "../types.js";
import { concatSlots, type FfmpegSettings } from "../lib/ffmpeg.js";
import { logger } from "../logger.js";

const ImageSourceSchema = z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("scene"), id: z.string() }),
  z.object({ kind: z.literal("broll"), id: z.string(), useFirstFrame: z.boolean().optional() }),
  z.object({ kind: z.literal("image"), id: z.string() }),
  z.object({ kind: z.literal("url"), url: z.string() }),
]);

export function registerAnimateTools(server: McpServer, ctx: Context): void {
  server.registerTool(
    "animate_image_to_video",
    {
      description: "Animate a still image into a short video via the configured animation provider (Veo). Saves the result as a b-roll clip so it can be dropped into any timeline slot via { kind: 'broll', id: <newClipId> }. Async — typically takes 30-90 seconds.",
      inputSchema: {
        imageSource: ImageSourceSchema.describe("Where the input image comes from. scene = scene asset, broll = first-frame thumbnail, image = generated image from generate_image, url = file:// or local path."),
        prompt: z.string().optional().describe("Cinematic motion description. e.g. 'slow zoom in, embers drifting, wind in cloak'. Defaults to subtle ambient motion."),
        durationSeconds: z.number().int().min(2).max(8).optional().describe("Output duration. Default 6. Veo 3 supports 4/6/8."),
        platform: z.enum(["mobile", "desktop"]).optional().describe("Determines aspect ratio (mobile=9:16, desktop=16:9). Defaults to config.defaults.platform."),
        description: z.string().optional().describe("Human-readable description for the b-roll library entry."),
        tags: z.array(z.string()).optional().describe("Tags for filtering in list_broll later."),
      },
    },
    async (args) => {
      const platform = (args.platform ?? ctx.config.defaults.platform) as Platform;
      const aspect = platform === "mobile" ? "9:16" : "16:9";
      const dims = PLATFORM_DIMENSIONS[platform];

      const { imageBytes, imageMimeType, sourceLabel } = await loadImageBytes(ctx, args.imageSource);

      const result = await ctx.animate().imageToVideo({
        imageBytes,
        imageMimeType,
        prompt: args.prompt,
        durationSeconds: args.durationSeconds,
        aspectRatio: aspect,
      });

      const id = `broll_veo_${randomUUID().slice(0, 8)}`;
      const written = await ctx.storage.writeBlob(`broll/${id}.mp4`, result.videoBytes);
      const clip: BRollClip = {
        id,
        url: written.url,
        filename: `${id}.mp4`,
        platform,
        durationSec: result.durationSeconds ?? args.durationSeconds ?? 6,
        description: args.description ?? `Veo animation of ${sourceLabel}${args.prompt ? ` — "${args.prompt}"` : ""}`,
        source: "veo-generated",
        tags: args.tags ?? ["generated", "veo"],
        veoRef: result.videoRef,
        veoModel: result.model,
        veoPrompt: args.prompt,
      };
      await ctx.index.putBRoll(clip);

      const uri = await ctx.storage.resolveUri(written.url);
      const extendable = platform === "desktop" && !!result.videoRef;
      return {
        content: [
          { type: "text", text:
            `clipId: ${id}\n` +
            `${platform} (${dims.width}x${dims.height}) | ${clip.durationSec}s | source: ${sourceLabel}\n` +
            `${clip.description}\n` +
            `uri: ${uri}\n` +
            (extendable ? `extendable: yes (call extend_video with brollId="${id}")\n` : `extendable: no (${platform === "mobile" ? "9:16 not supported by Veo extend API" : "no videoRef captured"})\n`) +
            `\nUse as a slot source: { "kind": "broll", "id": "${id}" }`,
          },
          { type: "resource_link", uri, name: clip.filename, mimeType: "video/mp4" },
        ],
      };
    },
  );

  server.registerTool(
    "extend_video",
    {
      description: "Extend a Veo-generated b-roll clip by chaining 1-10 continuation generations. Each extension calls Veo 3.1 with the previous video as input, producing a longer cumulative video. **16:9 desktop only — Veo extend API does not support 9:16 mobile.** Source clip must have been generated by animate_image_to_video (so it has a captured veoRef). Returns a NEW b-roll clip id with the extended video; the original is untouched.",
      inputSchema: {
        brollId: z.string().describe("Source b-roll clip id (must be Veo-generated and 16:9 desktop)"),
        extensions: z.number().int().min(1).max(10).describe("How many extension passes to chain (1-10). Each is a full Veo 3.1 generation — costs add up."),
        prompt: z.string().optional().describe("Motion prompt for the continuations. Defaults to the original clip's prompt, or generic ambient motion."),
        description: z.string().optional().describe("Description for the new b-roll record. Defaults to '<source description> — extended Nx'."),
        tags: z.array(z.string()).optional(),
      },
    },
    async (args) => {
      const source = await ctx.index.getBRoll(args.brollId);
      if (!source) {
        return { content: [{ type: "text", text: `No b-roll clip with id "${args.brollId}".` }], isError: true };
      }
      if (source.platform !== "desktop") {
        return { content: [{ type: "text", text: `Cannot extend "${args.brollId}": Veo extend API only supports 16:9 desktop, but this clip is ${source.platform} (9:16). Generate a desktop clip first.` }], isError: true };
      }
      if (!source.veoRef) {
        return { content: [{ type: "text", text: `Cannot extend "${args.brollId}": no captured veoRef. Only clips generated by animate_image_to_video (after the @google/genai SDK migration) have one. Re-generate the clip with animate_image_to_video.` }], isError: true };
      }
      const provider = ctx.animate();
      if (!provider.extendVideo) {
        return { content: [{ type: "text", text: `Configured animate provider "${provider.kind}" does not support extension.` }], isError: true };
      }
      const prompt = args.prompt ?? source.veoPrompt;
      const id = `broll_veo_ext_${randomUUID().slice(0, 8)}`;

      // Veo's extend API returns each continuation as its own ~8s segment, NOT the
      // cumulative video. We must persist every segment (seed first) and concat them
      // ourselves. Keeping only the last segment was the original bug — it produced
      // a clip the same length as the seed but with a different 8 seconds of motion.
      const seedLocal = await ctx.storage.resolveLocalPath(source.url);
      const segDir = `broll/ext_${id}`;
      const segPaths: string[] = [seedLocal];

      let currentRef: unknown = source.veoRef;
      let lastResult: { videoBytes: Buffer; videoRef?: unknown; model?: string } | undefined;
      for (let i = 1; i <= args.extensions; i++) {
        logger.info(`extend_video ${id}: extension ${i}/${args.extensions}`);
        const r = await provider.extendVideo({ previousVideoRef: currentRef, prompt });
        currentRef = r.videoRef;
        lastResult = r;
        const segRel = `${segDir}/seg_${String(i).padStart(2, "0")}.mp4`;
        const segLocal = await ctx.storage.localPathFor(segRel);
        writeFileSync(segLocal, r.videoBytes);
        segPaths.push(segLocal);
      }
      if (!lastResult) {
        return { content: [{ type: "text", text: `Extension loop produced no result.` }], isError: true };
      }

      // Concat seed + all extension segments into one continuous clip.
      const finalRel = `broll/${id}.mp4`;
      const finalLocal = await ctx.storage.localPathFor(finalRel);
      logger.info(`extend_video ${id}: concatenating ${segPaths.length} segments (1 seed + ${args.extensions} extensions)`);
      await concatSlots({
        slotPaths: segPaths,
        outputPath: finalLocal,
        settings: ctx.config.ffmpeg as FfmpegSettings,
      });

      const description = args.description ?? `${source.description} — extended ${args.extensions}x`;
      const clip: BRollClip = {
        id,
        url: finalRel,
        filename: `${id}.mp4`,
        platform: source.platform,
        durationSec: 0, // unknown until we probe; user can override
        description,
        source: "veo-generated",
        tags: args.tags ?? [...(source.tags ?? []), `extended-${args.extensions}x`],
        veoRef: lastResult.videoRef,
        veoModel: lastResult.model,
        veoPrompt: prompt,
        parentBrollId: source.id,
        extensionCount: (source.extensionCount ?? 0) + args.extensions,
      };
      await ctx.index.putBRoll(clip);

      const uri = await ctx.storage.resolveUri(finalRel);
      return {
        content: [
          { type: "text", text:
            `clipId: ${id}\n` +
            `extended ${args.extensions}x from ${source.id} (parent ${source.platform})\n` +
            `concatenated ${segPaths.length} segments (1 seed + ${args.extensions} extensions ≈ ${(segPaths.length * 8)}s)\n` +
            `${description}\n` +
            `uri: ${uri}\n` +
            `extendable: yes (chain further with extend_video brollId="${id}")\n\n` +
            `Use as a slot source: { "kind": "broll", "id": "${id}" }`,
          },
          { type: "resource_link", uri, name: clip.filename, mimeType: "video/mp4" },
        ],
      };
    },
  );
}

type ImageSource =
  | { kind: "scene"; id: string }
  | { kind: "broll"; id: string; useFirstFrame?: boolean }
  | { kind: "image"; id: string }
  | { kind: "url"; url: string };

async function loadImageBytes(ctx: Context, source: ImageSource): Promise<{ imageBytes: Buffer; imageMimeType: string; sourceLabel: string }> {
  if (source.kind === "scene") {
    const asset = await ctx.sceneAssets.getAsset(source.id);
    if (!asset) throw new Error(`No scene asset with id "${source.id}"`);
    if (asset.type === "video") throw new Error(`Scene asset "${source.id}" is a video, not an image. Cannot animate a video.`);
    const local = await ctx.storage.resolveLocalPath(asset.url);
    return { imageBytes: readFileSync(local), imageMimeType: mimeFromPath(local), sourceLabel: asset.label };
  }
  if (source.kind === "broll") {
    const clip = await ctx.index.getBRoll(source.id);
    if (!clip) throw new Error(`No b-roll clip with id "${source.id}"`);
    if (!clip.firstFrameUrl) {
      throw new Error(`B-roll clip "${source.id}" has no firstFrameUrl. Use { kind: "scene" } or { kind: "url" } to provide a still image directly.`);
    }
    const local = await ctx.storage.resolveLocalPath(clip.firstFrameUrl);
    return { imageBytes: readFileSync(local), imageMimeType: mimeFromPath(local), sourceLabel: `${clip.filename} (first frame)` };
  }
  if (source.kind === "image") {
    const image = await ctx.index.getImage(source.id);
    if (!image) throw new Error(`No generated image with id "${source.id}"`);
    const local = await ctx.storage.resolveLocalPath(image.url);
    return { imageBytes: readFileSync(local), imageMimeType: image.mimeType ?? mimeFromPath(local), sourceLabel: `image:${image.id}` };
  }
  if (source.kind === "url") {
    const local = await ctx.storage.resolveLocalPath(source.url);
    return { imageBytes: readFileSync(local), imageMimeType: mimeFromPath(local), sourceLabel: source.url };
  }
  throw new Error(`Unknown image source: ${JSON.stringify(source)}`);
}

function mimeFromPath(p: string): string {
  const ext = p.split(".").pop()?.toLowerCase() ?? "";
  switch (ext) {
    case "png": return "image/png";
    case "jpg":
    case "jpeg": return "image/jpeg";
    case "webp": return "image/webp";
    case "gif": return "image/gif";
    default: return "application/octet-stream";
  }
}
